projectName: dojo-forkserver
nameSpace: main
appType:
  frontend: webapp

replicaSet: 1

webappContainerService:
  type: ClusterIP  # {{ .Values.webappContainerService.type }}
  port: 3000       # {{ .Values.webappContainerService.port }}


domainName: oostvoort.work                # {{ .Values.domainName }}

subDomainName: 
  forkserver: forkserver.aw                 # {{ .Values.subDomainName.forkserver }}
  katana: katana.forkserver.aw           # {{ .Values.subDomainName.katana }}
  torii: torii.forkserver.aw             # {{ .Values.subDomainName.torii }}
  grpcTorii: grpc.forkserver.aw    # {{ .Values.subDomainName.grpcTorii }}


dockerImage: oostvoort/dojo-forkserver:latest